import './App.css'
import { useGenerateFact } from './hooks/useGenerateFact'
import { useGenerateImage } from './hooks/useGenerateImage'

function App () {
  const { fact, newFact } = useGenerateFact()
  const { imageUrl } = useGenerateImage({ fact })

  return (
    <main>
      <h1>Curious facts about cats</h1>
      <button onClick={newFact}>Get new random fact</button>
      {fact && <p>{fact}</p>}
      {imageUrl && <img alt={`A cat image generated by the first word of ${fact}`} src={imageUrl} />}
    </main>
  )
}

export default App
